---
- name: Customize database
  hosts: "{{ hostgroup | default('all') }}"
  become: true
  roles:
    - oradb_manage_pdb
    - oradb_manage_tablespace
    - oradb_manage_parameters
    - oradb_manage_redo
    - oradb_manage_roles
    - oradb_manage_users
    - oradb_manage_grants
    - oradb_manage_services
