---
- name: Host configuration
  hosts: drracattack-all
  user: root
  roles:
    # - common
    - orahost

- name: Storage Configuration
  hosts: drracattack-hub
  user: root
  roles:
    - orahost_storage

- name: Oracle Grid Infrastructure installation
  hosts: drracattack
  user: root
  roles:
    - oraswgi_install

- name: ASM Configuration, Database Server Installation & Database Creation
  hosts: drracattack-hub
  user: root
  roles:
    - oraasm_createdg
    - oraswdb_install
    # - oradb-create
