---
- name: Host configuration
  hosts: orarac-flex
  user: ansible
  become: true
  roles:
    - common
    - orahost

- name: Storage Configuration
  hosts: orarac-flex-hub
  user: ansible
  become: true
  roles:
    - orahost_storage

- name: Oracle Grid Infrastructure installation
  hosts: orarac-flex
  user: ansible
  become: true
  roles:
    - oraswgi_install

- name: ASM Configuration, Database Server Installation & Database Creation
  hosts: orarac-flex-hub
  user: ansible
  become: true
  roles:
    - oraasm_createdg
    - oraswdb_install
    - oradb_create
