---


- name: Host configuration
  hosts: "{{ hostgroup }}"
  become: true
  roles:
    - common
    - orahost
    - orahost_storage

- name: Oracle Grid Infrastructure installation & ASM Configuration
  hosts: "{{ hostgroup }}"
  become: true
  roles:
    - oraswgi_install
    - oraasm_createdg

- name: Database Server Installation & Database Creation
  hosts: "{{ hostgroup | default('all') }}"
  become: true
  roles:
    - oraswdb_install
    - oradb_manage_db

- name: Tweaks
  become: true
  hosts: "{{ hostgroup | default('all') }}"
  roles:
    - cxoracle
    - orahost_logrotate

# - name: Database configuration (tablespaces, parameters etc)
#   hosts: "{{ hostgroup }}"
#   become: yes
#   roles:
#       - oradb_parameters
#       - oradb_tablespace
#       - oradb_users
