---


- name: Host configuration
  hosts: "{{ hostgroup }}"
  become: true
  roles:
    - common
    - orahost
    - cxoracle

- name: Database Server Installation & Database Creation
  hosts: "{{ hostgroup }}"
  become: true
  roles:
    - oraswdb_install
    - oradb_manage_db
