---
- name: Host configuration
  hosts: vbox-rac-dc1
  user: vagrant
  become: true
  roles:
    - common
    - orahost

- name: ssh configuration
  hosts: vbox-rac-dc1
  user: vagrant
  become: true
  serial: 1
  roles:
    - {role: orahost_ssh, when: configure_cluster and not old_ssh_config}

- name: Storage Configuration
  hosts: vbox-rac-dc1
  user: vagrant
  become: true
  roles:
    - orahost_storage

- name: Oracle Grid Infrastructure installation
  hosts: vbox-rac-dc1
  user: vagrant
  become: true
  roles:
    - oraswgi_install

- name: Install cx_oracle
  hosts: vbox-rac-dc1
  user: vagrant
  become: true
  roles:
    - cxoracle

- name: ASM Diskgroup configuration
  hosts: vbox-rac-dc1
  user: vagrant
  become: true
  roles:
    - {role: oraasm_createdg, when: old_diskgroup_config}
    - {role: oraasm_manage_diskgroups, when: not old_diskgroup_config}


- name: Database Server Installation & Database Creation
  hosts: vbox-rac-dc1
  user: vagrant
  become: true
  roles:
    - oraswdb-install
    - {role: oraswdb_manage_patches, when: apply_patches_db}
    - oradb_manage_db

- name: Configure Logrotate
  hosts: vbox-rac-dc1
  user: vagrant
  become: true
  roles:
    - orahost_logrotate

- name: Customize database
  hosts: vbox-rac-dc1
  user: vagrant
  become: true
  roles:
    - oradb_manage_pdb
    - oradb_manage_tablespace
    - oradb_manage_parameters
    - oradb_manage_redo
    - oradb_manage_roles
    - oradb_manage_users
    - oradb_manage_grants
    - oradb_manage_services

- name: Run Datapatch
  hosts: vbox-si-rac-dc1
  user: vagrant
  become: true
  roles:
    - {role: oradb_datapatch, when: apply_patches_db}
