---

- name: Host configuration
  hosts: "{{ hostgroup | default('all') }}"
  become: true
  any_errors_fatal: true
  # collections:
  #   - opitzconsulting.ansible_oracle
  roles:
    - ../roles/common
    - ../roles/orahost
    - ../roles/orahost_storage
    - ../roles/orahost_ssh
    - ../roles/cxoracle
    - ../roles/orahost_logrotate

  post_tasks:
    - name: Restart autofs
      ansible.builtin.service:
        name: autofs
        enabled: true
        state: restarted
      tags: autofs
