---
- name: Oracle Grid Infrastructure / Restart installation & ASM Configuration
  hosts: "{{ hostgroup | default('all') }}"
  become: true
  any_errors_fatal: true
  # collections:
  #   - opitzconsulting.ansible_oracle
  roles:
    - ../roles/oraswgi_install
    - ../roles/oraswgi_manage_patches
    - ../roles/oraasm_manage_diskgroups
